networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop
  web:
    image: web:v1
    container_name: web
    networks:
      - roboshop
    ports:
      -  "80:80"
    